apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jvrjc6zxs-nodejs 
  janus-idp.io/tekton: jvrjc6zxs-nodejs
  backstage.io/kubernetes-id: jvrjc6zxs-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jvrjc6zxs-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  