apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jvrjc6zxs-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jvrjc6zxs-nodejs 
  name: jvrjc6zxs-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: jvrjc6zxs-nodejs 
